RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AWS Application Migration Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[markup.goldmark.renderer]
unsafe= true

[params]
  editURL = "https://github.com/aws-samples/application-migration-with-aws-workshop/edit/master/workshop/content/"
  description = "AWS Application Migration Workshop"
  author = "Ahmed Omran, Lech Migdal, Michitoshi Yoshida, Marcel van der Vliet, Diego Garcia Garcia, Jaroslaw Warzecha, Jonathan Trelles"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true


  [[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub Project"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Have questions?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Rate the workshop"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> More resources"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60


[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false

[Languages]
[Languages.en]
title = "AWS Application Migration Workshop"
weight = 40
languageName = "English"

[Languages.it]
title = "AWS Workshop per migrare le Applicazioni"
weight = 70
languageName = "Italiano"
  [[Languages.it.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Progetto GitHub"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.it.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Avete domande?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.it.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Fornisci commenti"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.it.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> Più risorse"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.ja]
title = "アプリケーション移行ワークショップ"
weight = 80
languageName = "Japanese（日本語）"

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub リポジトリ"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> 内容に関するお問い合わせ"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> ワークショップの評価"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> 参考資料"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.pt]
title = "Workshop de Migração de Aplicações da AWS"
weight = 90
languageName = "Português"

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Projeto GitHub"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Dúvidas?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Avalie este workshop"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> Mais recursos"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.zh]
title = "AWS 应用迁移研讨会"
weight = 10
languageName = "Chinese（简体中文）"

  [[Languages.zh.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub 项目"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.zh.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> 问题反馈"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.zh.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> 对研讨会进行评价"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.zh.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> 更多资源"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.es]
title = "Taller de migración de aplicaciones de AWS"
weight = 50
languageName = "Español"

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Proyecto GitHub"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> ¿Tiene Preguntas?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Califique el Taller"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.es.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> Más Recursos"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.fr]
title = "Workshop de migration d'applications de AWS"
weight = 60
languageName = "Français"

  [[Languages.fr.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Project GitHub"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.fr.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Avez-vous des questions ?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.fr.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Evaluez le workshop"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.fr.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> Plus de ressources"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.de]
title = "AWS Migrationsworkshop"
weight = 20
languageName = "Deutsch"

  [[Languages.de.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub Projekt"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.de.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Haben Sie fragen?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.de.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Workshop bewerten"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.de.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> Mehr Informationen"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60

[Languages.nl]
title = "AWS Application Migration Workshop"
weight = 85
languageName = "Nederlands"

  [[Languages.nl.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub Project"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.nl.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Heeft u vragen?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.nl.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Beoordeel de workshop"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.nl.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> Meer informatie"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60
